# Include at directory scope after creating the consumer target.
option(UDV_ENABLE_CUDA "Build UDV's primary CUDA backend when toolkit is available" ON)
option(UDV_REQUIRE_CUDA "Fail configure instead of producing a CPU-only fallback build" OFF)
set(UDV_CUDA_ARCHITECTURES "80-virtual;86-real" CACHE STRING "UDV CUDA architectures (Ampere baseline/PTX and RTX 3060 Ti native)")
if(UDV_ENABLE_CUDA)
  include(CheckLanguage)
  check_language(CUDA)
  if(CMAKE_CUDA_COMPILER)
    enable_language(CUDA)
    find_package(CUDAToolkit REQUIRED)
    add_library(udv_cuda STATIC "${CMAKE_CURRENT_LIST_DIR}/CudaCompute.cu")
    set_target_properties(udv_cuda PROPERTIES CUDA_STANDARD 17 CUDA_STANDARD_REQUIRED ON
      CUDA_RUNTIME_LIBRARY Static POSITION_INDEPENDENT_CODE ON
      CUDA_ARCHITECTURES "${UDV_CUDA_ARCHITECTURES}")
    target_compile_options(udv_cuda PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--fmad=false>)
    target_link_libraries(udv_cuda PUBLIC CUDA::cudart_static)
    target_link_libraries(${UDV_COMPUTE_TARGET} PRIVATE udv_cuda)
    target_compile_definitions(${UDV_COMPUTE_TARGET} PRIVATE UDV_HAS_CUDA=1)
  elseif(UDV_REQUIRE_CUDA)
    message(FATAL_ERROR "UDV primary backend requires CUDA; install a supported toolkit and MSVC toolset")
  else()
    message(WARNING "UDV: CUDA unavailable; this is an emergency CPU-only build. Use UDV_REQUIRE_CUDA=ON on the target PC.")
  endif()
elseif(UDV_REQUIRE_CUDA)
  message(FATAL_ERROR "UDV_REQUIRE_CUDA conflicts with UDV_ENABLE_CUDA=OFF")
endif()
